### ISSUE TITLE
Currently used location API not reliable

### ISSUE THREAD

**Issue by Tim-Abwao** [xofbd/wqu-weather-app#5]
`https://ipapi.co/{ip_address}/json` sometimes returns `null` for longitude and latitude. e.g. 

```json
    "postal": null,
    "latitude": null,
    "longitude": null,
    "timezone": null,
    "utc_offset": null,
```
This then causes problems because the weather API requires longitude and latitude values. With the 'null' location values, the weather API returns
>400 Bad Request
>The 'lat' parameter ("null") to Metno::WeatherAPI::Controller::Product::try {...}  did not pass regex check

which causes an **Internal Server Error** in the app, with error message

    json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

A possible alternative location API is <http://ip-api.com/>

**Comment by xofbd** [comment]
Thanks for raising this issue. One solution is to keep our current service but properly handle a situation where no location data was found.

Can we reproduce the error? Do you have any IP address ranges where this fails?

**Comment by Tim-Abwao** [comment]
<https://ipapi.co/197.156.137.180/json>

**Comment by gammaG2** [comment]
@Tim-Abwao thanks for the use-case relevant to this error.

I believe its better to fetch the lat long from the city-country name pair using `geopy` IF they are null in the first place.a `try except` block in the `get_location` function should do the trick!

**Comment by Tim-Abwao** [comment]
@gammaG2 I've tried an alternative geo-location API (in #10) which seems reliable so far with latitude and longitude data. It was simple to just switch the URL and a few lines of code.

**Comment by gammaG2** [comment]
Seems straight forward!

I think irrespective of which API we use, there is a possibility that the api response might be something unexpected once in a blue moon.

To address such issues, would a decorator function be a good idea to handle exceptions in each of the api dependant feature functions? @xofbd @Tim-Abwao

**Comment by xofbd** [comment]
Good conversations going one.

Crazy how it doesn't show the lat and lon for Nairobi, a city with several million people! Anyways I recommend:
1. using a new service
1. a decorator to handle those external API having some missing info. We should start putting any utility functions in a new `utils.py` file.
